#!/bin/bash
# coding: utf-8
# 参见《Bash4.0 参考文档》
echo -n "请输入一个动物的名称："
read ANIMAL
echo -n "$ANIMAL有"
case $ANIMAL in
    ( 马 | 狗 | 猫 ) 
        echo -n "四";;
    (人 | 袋鼠 | 鸡 | 鸭)
        echo -n "两";;
    (*)
        echo -n "未知数目的";;
esac
echo "腿。"

